### ISSUE TITLE
Original Freenet's plugins support

### ISSUE THREAD

**Issue by OveTomash84** [freenet-mobile/app#100]
**Is your feature request related to a problem? Please describe.**
After login Freenet there is a Wellcome Page with offer to install plugins. 
![IMG_20211101_190339](https://user-images.githubusercontent.com/93542395/139711100-40e46eee-703f-44c5-a608-159fc3e8b10e.jpg)
Unfortunately after clicking the link warning message with error appears. Also no link for plugins from main menu. 
![IMG_20211101_190412](https://user-images.githubusercontent.com/93542395/139711361-0b581f21-7534-4301-8bda-c37e4f61d22b.jpg)
So it is not clearly or it is an error or not supported feature. 

**Describe the solution you'd like**
Need to repair "Plugins" page to have possibility to use Sone and other. 

**Describe alternatives you've considered**
Or you can remove link to Plugins (and mention that plugins will be accessible later). 

**Additional
Android 11. Redmi.

**Comment by desyncr** [comment]
That's a good spot. Normal plugins are currently not supported by Freenet mobile. Although few of them are adapted to be loaded by the app and most of the official ones can be adapted as well.

The app will probably have an in-app plugin configuration page at that point. Meanwhile I'll disable the Plugins link as it's not usable.
