### ISSUE TITLE
Update FRED to build 1493.

### ISSUE THREAD

**Issue by Destroyinator69420** [freenet-mobile/app#117]
**Is your feature request related to a problem? Please describe.**
Freenet mobile still has no updated to the latest version of FRED. FRED 1493 brings improvements to the pitch black attack mitigation and updating the default index to Clean-Spider.

**Describe the solution you'd like**
Update the FRED contained in Freenet mobile to version 1493.

**Describe alternatives you've considered**
FRED could continue to stay at version 1492, but it would hamper integration with desktop nodes on the Freenet network.

**Comment by desyncr** [comment]
@Destroyinator69420 Updated in https://github.com/freenet-mobile/app/pull/118. Thanks for reporting.
