### ISSUE TITLE
Show version number

### ISSUE THREAD

**Issue by doublec** [freenet-mobile/app#12]
I can't seem to find the version number in the user interface. I've looked in settings and the main screen. The version number in the Android application manager entry shows 0.0.9 event though I'm running the latest release. Can it be added to the main screen or in the settings?

**Comment by desyncr** [comment]
@doublec Thanks for reporting. It was a thing that irked me for a while. I created [this task](https://github.com/freenet-mobile/app/projects/1) for it: About page, version number and some other contact information as well.

It'll be there for the next release for sure. At least the version number on the main screen.

**Comment by desyncr** [comment]
Fixed [here](https://github.com/freenet-mobile/app/commit/75a472eb4f3feffbd8b93711539684c4f3a3f95d) and released on [0.1.4](https://github.com/freenet-mobile/app/releases/tag/v0.1.4-beta).

Thanks for reporting :)
