### ISSUE TITLE
Release on f-droid and google play store

### ISSUE THREAD

**Issue by desyncr** [freenet-mobile/app#18]
RFP: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7353

**Comment by IzzySoft** [comment]
I just had to disable auto-updates at F-Droid as the tag name does not match versionName. So please decide for a "matching pattern". Initially, this was set to

```yaml
AutoUpdateMode: Version v%v
UpdateCheckMode: Tags v\d+\.\d+\.\d+(.*)?
```

which leads to `v0.2.1-beta` being ignored as viable candidate as it has `versionName "0.2.1"` (without the "-beta" suffix), and thus considering a "lower version" being the latest – for which no build block exists, leading to the annoyance of lint errors for each MR stating "current version lower than any we have".

So please keep tag name and version name in sync – i.e. either strip the "-beta" from the tag name, or add it to versionName as well. Once a matching tag exists let me know and I can re-enable update check. Thanks!

**Comment by desyncr** [comment]
Thanks for pointing out the exact issue! I'll update versionName to "0.2.1-beta" to it will match with the tag name.

Once I do that I'll release "0.2.2-beta", hopefully that version can be picked up automatically?

**Comment by IzzySoft** [comment]
@desyncr careful: better do NOT touch tags which have been built already, that can have nasty side-effects. So "yes" to 0.2.2-beta, but rather "no" to the current one.

And no: I've disabled auto-update as it currently would break things. Just ping me here once the next (correctly tagged/named) release is available, and after a cursory check I can enable updates again.

**Comment by desyncr** [comment]
@IzzySoft I've ready the 0.2.2-beta release:
```
versionCode 293
versionName "v0.2.2-beta"
```
Tag: `v0.2.2-beta`

Good to go?

**Comment by IzzySoft** [comment]
Principially it should. Please make sure now which versioning schema you wish to use. What you wrote now means we also need to change to

```yaml
AutoUpdateMode: Version %v
```

as `tag name == versionName` (you've added the `v` in `versionName` as well now). If you rather want to go with `tagName = "v<versionName>"`, then you should change your `build.gradle` accordingly to

```gradle
versionCode 293
versionName "0.2.2-beta"
```

Choose what you wish to stick with, so we don't have to change that manually with each release :wink:

**Comment by desyncr** [comment]
@IzzySoft Oh, I forgot about that last piece. Yeah,  I'll go with `tagName = "v<versionName>"`:
```
versionCode 293
versionName "0.2.2-beta"
```
^ Already in master.

Tag: `v0.2.2-beta`
^ Not created yet.

```
AutoUpdateMode: Version v%v
```
^ As it's now.

**Comment by IzzySoft** [comment]
Thought so, just wanted to make sure :smile: Let me know when you think all is ready and I should check if we can re-enable auto update accordingly.

**Comment by desyncr** [comment]
Everything is ready. I'll do the release in a few hours.

**Comment by desyncr** [comment]
Done @IzzySoft Hopefully no errors will popup this time.

**Comment by IzzySoft** [comment]
Looks good. Keep :crossed_fingers: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8236

**Comment by desyncr** [comment]
Looking good https://f-droid.org/en/packages/org.freenetproject.mobile/ 🥳

**Comment by desyncr** [comment]
Thanks @IzzySoft for the huge help getting this done! 👊

**Comment by IzzySoft** [comment]
Yay! :hugs:
