### ISSUE TITLE
"Error starting Freenet" after it successfully started

### ISSUE THREAD

**Issue by mkb2091** [freenet-mobile/app#33]
Often, (but not always) when re-opening the app after having already started it, it says "Error starting Freenet. Restart the application and try again. If the error persists reinstall the application". Freenet still works if I open a browser and go to 127.0.0.1:8888, but the button to open it in a browser is gone while it is displaying that error. On the web interface clicking the shutdown button causes it to stop, and have the Start Freenet button when the app is next opened, as expected

**Comment by desyncr** [comment]
So, the steps would be as follows:

1) Start the app (with the node not running at this point)
2) Start the node (it will show "node running" message)
3) Close the app
4) Open the app again

Expected:
- "node running" message is displayed
- The "pause" button is displayed

Actual:
- "error starting" message is shown

Can you provide the android version you're using Freenet mobile on?

**Comment by mkb2091** [comment]
I'm running android 8.0.0. 

I've been attempting to duplicate the error, and found a different set of steps which cause the error every time for me:

1. Start charging phone
2. Start the app (with the node not running at this point)
3. Turn on "Preserve Battery"
4. Start the node (it will show "node running" message)
5. Interrupt charging by removing cable

OR

1. Start the app (with the node not running at this point)
2. Turn on "Preserve Battery"
3. Start the node (it will show "node running" message)
- No error yet
4. Start charging phone
5. Interrupt charging by removing cable

Expected:
- "node running" message is displayed
- The "pause" button is displayed

Actual:
- "error starting" message is shown

I've found turning off "Preserve Battery" before starting the node seems to causes the error to not appear

I have a not perfect cable/charging port which means that slightly moving the phone can cause it to stop charging, making it seem like the app just had the error in the background.

The notification that says "Freenet is running You're connected to the Freenet network" still displays as expected.
