### ISSUE TITLE
Darknet is not stopped by Preserve Battery 

### ISSUE THREAD

**Issue by mkb2091** [freenet-mobile/app#34]
I have Preserve Battery enabled. When I unplug the phone, then opennet is disabled, but darknet is still enabled, meaning it is still running Freenet and sending/receiving data to darknet nodes it is connected it. I'm assuming this will mean it will continue to use power.

**Comment by desyncr** [comment]
That's right. Opennet is disabled and darknet will continue to work.

Currently there's no way to stop the darknet node, so yes, it's gonna consume both battery and network as well.

What I'll do is to clarify this on the app itself.
