### ISSUE TITLE
please take care for your versionCode!

### ISSUE THREAD

**Issue by IzzySoft** [freenet-mobile/app#59]
your latest release, v0.2.2beta, has [`versionCode 293`](org.freenetproject.mobile). The previous one, v0.2.1beta, had `versionCode 295` – thus you DECREASED it – which is an absolute no-go: Android refuses to accept this as update, as it considers it a downgrade. Please fix ASAP (setting `versionCode` to 296 or higher) – and please also replace the APK then :wink: Thanks!

**Comment by desyncr** [comment]
Thanks for the heads up. Do you think it's better to release a new version (v0.2.3beta) with proper versionCode (say, 296) or to try to fix the current one (v0.2.2beta)? I would need to remove the tag as well and update the release attachments, right?

**Comment by IzzySoft** [comment]
Making a new release suffices. I'd also remove the "broken one", yes – but "fixing it" is wasted time if a new release is ready.

**Comment by desyncr** [comment]
New version released!

**Comment by IzzySoft** [comment]
My updater did not complain, so it seems you've successfully solved the issue :smiley:
