### ISSUE TITLE
F-Droid can't build due to 'https://mvn.freenetproject.org'

### ISSUE THREAD

**Issue by linsui** [freenet-mobile/app#89]
**Describe the bug**
'https://mvn.freenetproject.org' is not a trust maven repo so that F-Droid can't build it.

Can those dependencies be built along with the app or download a [trusted maven repo](https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/scanner.py#L152)? Thanks!

**Comment by desyncr** [comment]
I think we're  getting our dependencies from jitpack mostly, so I'll check it out.

**Comment by desyncr** [comment]
@linsui Solved. Published v0.3.4 successfully. Thanks for the report :+1:
